# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78df56f2ad2d3ff7a5bef26e9628293c73f91dabaa51239a3d3656d364f35a15943db2814cc6091b766f5250c33c462a1f1b8cc502187761572cb0b54f03effc

test:
  secret_key_base: f2e1c3ff29f300b88ff84cb4f4705308ed7b6832317e90aad72dd8409c4a4bec41f18747a99559fa2cf792e158c940bc43e8fa687ee96fb3873986e8f77ede55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
